### ISSUE TITLE
setup.sh doesn't work with Cloudflare

### ISSUE THREAD

**Issue by 1zaak** [jacobobryant/biff#150]
I followed the tutorial and can't seem to make Cloudflare to work with certbot. Tried using CSR (origin cert in Cloudflare) but still didn't work. 

Step 7 in [deploy](https://biffweb.com/docs/tutorial/deploy/) of uploading the code to the server is the problem. It seems it can't point to my domain properly. 

Essentially I can't ssh using the domain (instead of IP).

`git remote add prod ssh://app@eelchat.biffweb.com/home/app/repo.git`

`ssh: connect to host [redacted.xyz] port 22: Operation timed out`

**Comment by jacobobryant** [comment]
I only have a passing familiarity with using Cloudflare--am I correct in assuming that your domain is pointed at a Cloudflare IP address rather than at your server's IP? In steps 5 and 6, were you able to run the `scp` / `ssh` commands using your domain, or did you use your server's IP address instead? Assuming you used the IP address and that worked fine, you should be able to do the same in step 7 I believe.

As for step 6 of actually running `setup.sh`, I'm assuming you'd need to comment out the `certbot` bit and follow [Cloudflare's instructions](https://developers.cloudflare.com/ssl/origin-configuration/origin-ca/) for installing a cert on your server.

**Comment by 1zaak** [comment]
Thanks @jacobobryant 

So I just forgo using cloudflare completely, seems an unnecessary hassle. And it works.

But now I'm getting this when I `bb deploy`:

`fatal: invalid refspec ''
Error while executing task: deploy`

**Comment by 1zaak** [comment]
Sorry my bad, it was a typo when I uncomment the task

`biff.tasks/deploy-cmd ["git" "push" "prod" "main:master"]`

It's missing a colon 😂

**Comment by jacobobryant** [comment]
ah, glad you got it working!
