### ISSUE TITLE
How to use Biff with datomic? Any example?

### ISSUE THREAD

**Issue by vldmr-k** [jacobobryant/biff#169]

**Comment by jacobobryant** [comment]
No examples yet but it is on the roadmap--I'm planning to write up a how-to for this as part of my current grant from clojurists together actually. Basically you just create a new project and then go through all the generated files and replace all transactions and queries with calls to datomic. You'll also need to modify the authentication plugin so that it uses datomic instead of xt. I'll leave this issue open the how-to is published.

**Comment by vldmr-k** [comment]
Thank you @jacobobryant

**Comment by jacobobryant** [comment]
I've published this post which demonstrates replacing XTDB with Postgres: https://biffweb.com/p/how-to-use-postgres-with-biff/

I probably won't get around to writing a similar how-to for Datomic, but you can use that one as a guide. It shows you all the places that need to be updated; you'll just need to update those spots with Datomic code instead of Postgres code.

(If you do go through that process and you publish an example repo, send me a link and I'll put it on the [content library](https://biffweb.com/docs/library/).)
