### ISSUE TITLE
Question: Live reloading of custom config

### ISSUE THREAD

**Issue by mjholub** [jacobobryant/biff#226]
Hello,  
I am building an admin dashboard for my app.  
This involves manipulating the settings file. What I currently do is use this wrapper that merges the framework-specific config and secrets with what can be read by a standard edn reader since I don't want to bother processing the values from all the `fn`s returned by a crude `use-aero-config` call, plus it's a little bit more secure to keep the part of config that can be manipulated over HTTP in a separate file.
```clojure
(defn load-edn
  "Loads edn from an io/reader source (filename or io/resource)."
  [source-file]
  (try
    (with-open [r (io/reader source-file)]
      (edn/read (java.io.PushbackReader. r)))
    (catch java.io.IOException e
      (log/errorf "Couldn't open '%s': %s\n" source-file (.getMessage e)))
    (catch RuntimeException e
      (log/errorf "Error parsing edn file '%s': %s\n" source-file (.getMessage e)))))
```
```clojure
(defn use-custom-config [system]
  (let [base-config (biff/use-aero-config system)
        custom-config (load-edn "resources/user-config.edn")
        merged-config (merge base-config custom-config)
        ]
    (merge system merged-config)
    )
  )

(def components
  [use-custom-config
   biff/use-xtdb
   biff/use-queues
   biff/use-xtdb-tx-listener
   biff/use-htmx-refresh
   biff/use-jetty
   biff/use-chime
   biff/use-beholder])

(defn start []
  (let [new-system (reduce (fn [system component]
                             (log/info "starting:" (str component))
                             (component system))
                           initial-system
                           components)]
    (reset! system new-system)
    (generate-assets! new-system)
    (log/info "System started.")
    (log/info "Go to " (:biff/base-url new-system))
    new-system))
```

Then the data is processed by the appropriate endpoint that backs up the old file and overwrites the old one. 
```clojure
(defn save [ctx]
  (let [params (transform-params (dissoc (:params ctx) :__anti-forgery-token))
        existing-settings (load-edn "resources/user-config.edn")
        updated (into (sorted-map-by compare-keys) (incremental-update existing-settings params))
        ]
    (spit "resources/user-config.edn.bak" (str/replace (str existing-settings) #", " " \n"))
    (spit "resources/user-config.edn" (str/replace (str updated) #", " " \n"))
  {:status 201
   :body "Settings saved!"
   })
  )
```

The settings changes are visible after the app is restarted, but I want to be able to reload the context map so that it 'has' the new values without restarting (so that my dashboard GUI isn't just a glorified text editor). Can I achieve that without resorting to a blue/green deployment?

PS. fwiw a reload triggered by a watched file modification does not affect the loaded configuration.

**Comment by jacobobryant** [comment]
There are a couple ways you could go about this. First, just to double check: do you definitely want the settings to be stored in an edn file, or could you just put them in the database? You could also add an import/export feature into the admin dashboard that lets you upload/download edn files.

If you do want to store the dashboard settings in an edn file, one option would be to store them in an atom:

```clojure
;; in your main namespace
(def initial-system
  {...
   :com.example/dashboard-settings (atom {})})

;; in your application namespaces
(defn save [{:keys [com.example/dashboard-settings] :as ctx}]
  (let [updated ...]
    (spit ...)
    (reset! dashboard-settings updated)
    {:status 201
     :body "Settings saved!"}))

(defn my-handler [{:keys [com.example/dashboard-settings] :as ctx}]
  (let [{:keys [some-setting]} @dashboard-settings]
    ...))
```

(and then also have `use-custom-config` populate the atom on startup)

Another option is to provide a custom value for `:biff/merge-context-fn`:

```clojure
(defn read-custom-config []
  (edn/read-string (slurp "resources/user-config.edn")))

(defn merge-context [ctx]
  (-> ctx
      (biff/assoc-db)
      (merge (read-custom-config))))

(def initial-system
  {...
   :biff/merge-context-fn #'merge-context})
```

By default, that function just does a `biff/assoc-db` call which adds the `:biff/db` value to your context map so you don't have to do it yourself. Biff calls that function in various places, basically whenever it's about to pass `ctx` to your application code. e.g. the `use-jetty` component calls `:biff/merge-context-fn` before it passes the request to your ring handlers: https://github.com/jacobobryant/biff/blob/a1d53efdab2046134575b71ed35a51fbcd212600/src/com/biffweb/impl/misc.clj#L76.

so if you have `merge-context` add the custom config to your context map, then it'll run every time you get a new request. It would be basically the same as writing some middleware that merges the custom config into incoming requests. The downside of course is that you're then reading this file a lot more than you have to. So I'd probably modify `read-custom-config` so that it caches the result based on the file's modified time, something like:

```clojure
(let [cache (atom {})]
  (defn read-custom-config []
    (let [last-modified (.lastModified (io/file "deps.edn"))
          {:keys [config cached-at]} @cache]
      (if (= cached-at last-modified)
        config
        (:config (reset! cache {:cached-at last-modified
                                :config (edn/read-string (slurp "resources/user-config.edn"))}))))))
```

The `:com.example/dashboard-settings (atom {})` approach is simpler IMO, but a benefit of the `merge-context` approach is that you don't have to make sure you update the atom whenever you update the config. e.g. you could even update the config via a text editor and your app would immediately pick up the changes.

**Comment by mjholub** [comment]
Thanks a lot! I will check this out.
