### ISSUE TITLE
application cant find env variables 

### ISSUE THREAD

**Issue by drewverlee** [jacobobryant/biff#70]
Greetings

config/task.env is initially created without "export ..." before each var. Which should be fine, i imagine .env files are supposed to work that way. But the rest of the application seems (i haven't checked) to and possibly execute it like a bash file.

This confusion results in /task build-image failing because it can't find the digitalocean key. You can reproduce this by following the getting started instructions

1. bash <(curl -s https://raw.githubusercontent.com/jacobobryant/biff/master/new-project.sh)
2.  ./task init
3. ./task dev
4. ./task build-image

I'll see if i can put together a patch. shouldn't be hard assuming we agree on the root issue.

**Comment by jacobobryant** [comment]
Thanks for catching this. I recently removed the `export`s as a minor security improvement since they aren't needed for the build tasks, since `task.env` is included via `source`:

https://github.com/jacobobryant/biff/blob/71682e5e3ba9fa5eaa4586666d9cd469e1d4cdba/resources/biff/project/base/%7B%7Bdir%7D%7D/task#L4-L6

Or at least, the `export`s are *supposed* to not be needed--obviously I missed a case. I've fixed it in https://github.com/jacobobryant/biff/commit/71682e5e3ba9fa5eaa4586666d9cd469e1d4cdba

(I also removed another `export` that I missed before)

As an aside, I also just made this issue: https://github.com/jacobobryant/biff/issues/71
